# Generated by Django 2.2.1 on 2019-07-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='create',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
