# Generated by Django 2.2.1 on 2019-06-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_auto_20190628_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='token',
        ),
    ]
